export type CatalogLanguage = {
  name: string;
  code: string;
  popular: boolean;
};

const POPULAR: CatalogLanguage[] = [
  { name: "English", code: "en", popular: true },
  { name: "Spanish", code: "es", popular: true },
  { name: "Portuguese", code: "pt", popular: true },
  { name: "French", code: "fr", popular: true },
  { name: "German", code: "de", popular: true },
  { name: "Italian", code: "it", popular: true },
  { name: "Dutch", code: "nl", popular: true },
  { name: "Chinese", code: "zh", popular: true },
  { name: "Japanese", code: "ja", popular: true },
  { name: "Korean", code: "ko", popular: true },
];

const MORE: CatalogLanguage[] = [
  { name: "(Eastern) Punjabi", code: "pa", popular: false },
  { name: "Abkhaz", code: "ab", popular: false },
  { name: "Afar", code: "aa", popular: false },
  { name: "Afrikaans", code: "af", popular: false },
  { name: "Akan", code: "ak", popular: false },
  { name: "Albanian", code: "sq", popular: false },
  { name: "Amharic", code: "am", popular: false },
  { name: "Arabic", code: "ar", popular: false },
  { name: "Aragonese", code: "an", popular: false },
  { name: "Armenian", code: "hy", popular: false },
  { name: "Assamese", code: "as", popular: false },
  { name: "Avaric", code: "av", popular: false },
  { name: "Avestan", code: "ae", popular: false },
  { name: "Aymara", code: "ay", popular: false },
  { name: "Azerbaijani", code: "az", popular: false },
  { name: "Bambara", code: "bm", popular: false },
  { name: "Bashkir", code: "ba", popular: false },
  { name: "Basque", code: "eu", popular: false },
  { name: "Belarusian", code: "be", popular: false },
  { name: "Bengali, Bangla", code: "bn", popular: false },
  { name: "Bihari", code: "bh", popular: false },
  { name: "Bislama", code: "bi", popular: false },
  { name: "Bosnian", code: "bs", popular: false },
  { name: "Breton", code: "br", popular: false },
  { name: "Bulgarian", code: "bg", popular: false },
  { name: "Burmese", code: "my", popular: false },
  { name: "Catalan", code: "ca", popular: false },
  { name: "Chamorro", code: "ch", popular: false },
  { name: "Chechen", code: "ce", popular: false },
  { name: "Chichewa, Chewa, Nyanja", code: "ny", popular: false },
  { name: "Chuvash", code: "cv", popular: false },
  { name: "Cornish", code: "kw", popular: false },
  { name: "Corsican", code: "co", popular: false },
  { name: "Cree", code: "cr", popular: false },
  { name: "Croatian", code: "hr", popular: false },
  { name: "Czech", code: "cs", popular: false },
  { name: "Danish", code: "da", popular: false },
  { name: "Divehi, Dhivehi, Maldivian", code: "dv", popular: false },
  { name: "Dzongkha", code: "dz", popular: false },
  { name: "Esperanto", code: "eo", popular: false },
  { name: "Estonian", code: "et", popular: false },
  { name: "Ewe", code: "ee", popular: false },
  { name: "Faroese", code: "fo", popular: false },
  { name: "Fijian", code: "fj", popular: false },
  { name: "Finnish", code: "fi", popular: false },
  { name: "Fula, Fulah, Pulaar, Pular", code: "ff", popular: false },
  { name: "Galician", code: "gl", popular: false },
  { name: "Ganda", code: "lg", popular: false },
  { name: "Georgian", code: "ka", popular: false },
  { name: "Greek (modern)", code: "el", popular: false },
  { name: "Guaraní", code: "gn", popular: false },
  { name: "Gujarati", code: "gu", popular: false },
  { name: "Haitian, Haitian Creole", code: "ht", popular: false },
  { name: "Hausa", code: "ha", popular: false },
  { name: "Hebrew (modern)", code: "he", popular: false },
  { name: "Herero", code: "hz", popular: false },
  { name: "Hindi", code: "hi", popular: false },
  { name: "Hiri Motu", code: "ho", popular: false },
  { name: "Hungarian", code: "hu", popular: false },
  { name: "Icelandic", code: "is", popular: false },
  { name: "Ido", code: "io", popular: false },
  { name: "Igbo", code: "ig", popular: false },
  { name: "Indonesian", code: "id", popular: false },
  { name: "Interlingua", code: "ia", popular: false },
  { name: "Interlingue", code: "ie", popular: false },
  { name: "Inuktitut", code: "iu", popular: false },
  { name: "Inupiaq", code: "ik", popular: false },
  { name: "Irish", code: "ga", popular: false },
  { name: "Javanese", code: "jv", popular: false },
  { name: "Kalaallisut, Greenlandic", code: "kl", popular: false },
  { name: "Kannada", code: "kn", popular: false },
  { name: "Kanuri", code: "kr", popular: false },
  { name: "Kashmiri", code: "ks", popular: false },
  { name: "Kazakh", code: "kk", popular: false },
  { name: "Khmer", code: "km", popular: false },
  { name: "Kikuyu, Gikuyu", code: "ki", popular: false },
  { name: "Kinyarwanda", code: "rw", popular: false },
  { name: "Kirundi", code: "rn", popular: false },
  { name: "Komi", code: "kv", popular: false },
  { name: "Kongo", code: "kg", popular: false },
  { name: "Kurdish", code: "ku", popular: false },
  { name: "Kwanyama, Kuanyama", code: "kj", popular: false },
  { name: "Kyrgyz", code: "ky", popular: false },
  { name: "Lao", code: "lo", popular: false },
  { name: "Latin", code: "la", popular: false },
  { name: "Latvian", code: "lv", popular: false },
  { name: "Limburgish, Limburgan, Limburger", code: "li", popular: false },
  { name: "Lingala", code: "ln", popular: false },
  { name: "Lithuanian", code: "lt", popular: false },
  { name: "Luba-Katanga", code: "lu", popular: false },
  { name: "Luxembourgish, Letzeburgesch", code: "lb", popular: false },
  { name: "Macedonian", code: "mk", popular: false },
  { name: "Malagasy", code: "mg", popular: false },
  { name: "Malay", code: "ms", popular: false },
  { name: "Malayalam", code: "ml", popular: false },
  { name: "Maltese", code: "mt", popular: false },
  { name: "Manx", code: "gv", popular: false },
  { name: "Māori", code: "mi", popular: false },
  { name: "Marathi (Marāṭhī)", code: "mr", popular: false },
  { name: "Marshallese", code: "mh", popular: false },
  { name: "Mongolian", code: "mn", popular: false },
  { name: "Nauruan", code: "na", popular: false },
  { name: "Navajo, Navaho", code: "nv", popular: false },
  { name: "Ndonga", code: "ng", popular: false },
  { name: "Nepali", code: "ne", popular: false },
  { name: "Northern Ndebele", code: "nd", popular: false },
  { name: "Northern Sami", code: "se", popular: false },
  { name: "Norwegian", code: "no", popular: false },
  { name: "Norwegian Bokmål", code: "nb", popular: false },
  { name: "Norwegian Nynorsk", code: "nn", popular: false },
  { name: "Nuosu", code: "ii", popular: false },
  { name: "Occitan", code: "oc", popular: false },
  { name: "Ojibwe, Ojibwa", code: "oj", popular: false },
  { name: "Old Church Slavonic, Church Slavonic, Old Bulgarian", code: "cu", popular: false },
  { name: "Oriya", code: "or", popular: false },
  { name: "Oromo", code: "om", popular: false },
  { name: "Ossetian, Ossetic", code: "os", popular: false },
  { name: "Pāli", code: "pi", popular: false },
  { name: "Pashto, Pushto", code: "ps", popular: false },
  { name: "Persian (Farsi)", code: "fa", popular: false },
  { name: "Polish", code: "pl", popular: false },
  { name: "Portuguese (Portugal)", code: "pt-PT", popular: false },
  { name: "Quechua", code: "qu", popular: false },
  { name: "Romanian", code: "ro", popular: false },
  { name: "Romansh", code: "rm", popular: false },
  { name: "Russian", code: "ru", popular: false },
  { name: "Samoan", code: "sm", popular: false },
  { name: "Sango", code: "sg", popular: false },
  { name: "Sanskrit (Saṁskṛta)", code: "sa", popular: false },
  { name: "Sardinian", code: "sc", popular: false },
  { name: "Scottish Gaelic, Gaelic", code: "gd", popular: false },
  { name: "Serbian", code: "sr", popular: false },
  { name: "Shona", code: "sn", popular: false },
  { name: "Sindhi", code: "sd", popular: false },
  { name: "Sinhalese, Sinhala", code: "si", popular: false },
  { name: "Slovak", code: "sk", popular: false },
  { name: "Slovene", code: "sl", popular: false },
  { name: "Somali", code: "so", popular: false },
  { name: "Southern Ndebele", code: "nr", popular: false },
  { name: "Southern Sotho", code: "st", popular: false },
  { name: "Sundanese", code: "su", popular: false },
  { name: "Swahili", code: "sw", popular: false },
  { name: "Swati", code: "ss", popular: false },
  { name: "Swedish", code: "sv", popular: false },
  { name: "Tagalog", code: "tl", popular: false },
  { name: "Tahitian", code: "ty", popular: false },
  { name: "Tajik", code: "tg", popular: false },
  { name: "Tamil", code: "ta", popular: false },
  { name: "Tatar", code: "tt", popular: false },
  { name: "Telugu", code: "te", popular: false },
  { name: "Thai", code: "th", popular: false },
  { name: "Tibetan Standard, Tibetan, Central", code: "bo", popular: false },
  { name: "Tigrinya", code: "ti", popular: false },
  { name: "Tonga (Tonga Islands)", code: "to", popular: false },
  { name: "Tsonga", code: "ts", popular: false },
  { name: "Tswana", code: "tn", popular: false },
  { name: "Turkish", code: "tr", popular: false },
  { name: "Turkmen", code: "tk", popular: false },
  { name: "Twi", code: "tw", popular: false },
  { name: "Ukrainian", code: "uk", popular: false },
  { name: "Urdu", code: "ur", popular: false },
  { name: "Uyghur", code: "ug", popular: false },
  { name: "Uzbek", code: "uz", popular: false },
  { name: "Venda", code: "ve", popular: false },
  { name: "Vietnamese", code: "vi", popular: false },
  { name: "Volapük", code: "vo", popular: false },
  { name: "Walloon", code: "wa", popular: false },
  { name: "Welsh", code: "cy", popular: false },
  { name: "Western Frisian", code: "fy", popular: false },
  { name: "Wolof", code: "wo", popular: false },
  { name: "Xhosa", code: "xh", popular: false },
  { name: "Yiddish", code: "yi", popular: false },
  { name: "Yoruba", code: "yo", popular: false },
  { name: "Zhuang, Chuang", code: "za", popular: false },
  { name: "Zulu", code: "zu", popular: false },
];

export const CATALOG_LANGUAGES: CatalogLanguage[] = [...POPULAR, ...MORE];

const BY_CODE = new Map(CATALOG_LANGUAGES.map((language) => [language.code, language]));

export function catalogLanguage(code: string) {
  return BY_CODE.get(code);
}

export function isCatalogLanguage(code: string) {
  return BY_CODE.has(code);
}
